version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ci-cd"

  - package-ecosystem: "composer"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    labels:
      - "dependencies"
      - "composer"
    ignore:
      - dependency-name: "symfony/*"
        versions: [">=7.0"]
    groups:
      composer-require:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      composer-require-dev:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
      - "npm"
    allow:
      - dependency-type: "direct"
    groups:
      npm-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      npm-dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
