name: Release Assets to WP.org

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Push Assets to WordPress.org
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SLUG: syntatis-feature-flipper
          ASSETS_DIR: .wporg
          IGNORE_OTHER_FILES: true
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
