name: Release to WP.org

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  PLUGIN_SLUG: syntatis-feature-flipper

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer:v2

      - name: Install dependencies
        run: |
          npm install
          composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Build plugin
        run: |
          npm run build
          composer run build
          composer run zip -- --file=build
          unzip build.zip -d build

      - name: Setup PHP for release checks
        if: ${{ github.event_name == 'release' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer:v2

      - name: Install version checker
        if: ${{ github.event_name == 'release' }}
        run: |
          mkdir -p /tmp/consistent-versions
          composer require --working-dir=/tmp/consistent-versions szepeviktor/consistent-versions --no-interaction --no-progress

      - name: "Check latest tagged version"
        if: ${{ github.event_name == 'release' }}
        run: /tmp/consistent-versions/vendor/bin/consistent-versions check consistent-versions.release.yaml

      - name: Deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: ${{ github.event_name != 'release' }}
        env:
          ASSETS_DIR: .wporg
          BUILD_DIR: build
          SLUG: ${{ env.PLUGIN_SLUG }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
