name: release

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  PLUGIN_SLUG: syntatis-feature-flipper

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer:v2

      - name: Install dependencies
        run: |
          npm ci
          composer i --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Build plugin
        run: |
          npm run build
          composer run build
          composer run plugin:zip -- --file=build.zip
          unzip build.zip

      - name: Deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: ${{ github.event_name != 'release' }}
        env:
          ASSETS_DIR: .wporg
          BUILD_DIR: build
          SLUG: ${{ env.PLUGIN_SLUG }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
